### ISSUE TITLE
Change WiFi raPo

### ISSUE THREAD

**Issue by dronenb** [samuelthomas2774/airport#1]
Any idea how to change the raPo (transmit) of the WiFi property using acp? You used to be able to do this with old versions of the AirPort utility but you are no longer able to in the latest version.  (Side note: love this wiki, thanks for all of your work).

**Comment by samuelthomas2774** [comment]
The `WiFi` property (and some other properties with binary property lists that are configurable in AirPort Utility) seems to be read only with the set property command. AirPort Utility uses RPC commands to update configuration which isn't supported in node-acp yet.

I would suggest using AirPort Utility's configuration import/export feature for now. You can backup the configuration (unencrypted) to an XML property list, edit it and then restore everything from that configuration file. (That's what I do to get more advanced configurations.)

**Comment by dronenb** [comment]
Good looks. Guess I'll close this issue then. Thanks!
