### ISSUE TITLE
No matching host key type found

### ISSUE THREAD

**Issue by Kai-Denzel-Jane** [samuelthomas2774/airport#10]
I cant seem to ssh into my AirPort using node-acp its as if I need an SSH Key.
Ive gotten this working in the past but I have no clue on how I got it to work.

Here's the final error message:

Unable to negotiate with 10.1.1.157 port 22: no matching host key type found. Their offer: ssh-rsa,ssh-dss

I can provide verbose logs if necessary thanks in advance.

**Comment by samuelthomas2774** [comment]
> ```
> Unable to negotiate with 10.1.1.157 port 22: no matching host key type found. Their offer: ssh-rsa,ssh-dss
> ```

"matching" here is a bit confusing, what this actually means is that the server offered `ssh-rsa` and `ssh-dss` keys, but you are refusing to use any of these types of keys (they're disabled by default in newer versions of ssh).

Add `-o HostKeyAlgorithms=+ssh-rsa` to the ssh command (or add `HostKeyAlgorithms=+ssh-rsa` to a section for the AirPort in `~/.ssh/config`) to allow it to connect.

(Added to wiki: https://github.com/samuelthomas2774/airport/wiki/SSH#airport-host-key-types.)

**Comment by Kai-Denzel-Jane** [comment]
> > ```
> 
> > Unable to negotiate with 10.1.1.157 port 22: no matching host key type found. Their offer: ssh-rsa,ssh-dss
> 
> > ```
> 
> 
> 
> "matching" here is a bit confusing, what this actually means is that the server offered `ssh-rsa` and `ssh-dss` keys, but you are refusing to use any of these types of keys (they're disabled by default in newer versions of ssh).
> 
> 
> 
> Add `-o HostKeyAlgorithms=+ssh-rsa` to the ssh command (or add `HostKeyAlgorithms=+ssh-rsa` to a section for the AirPort in `~/.ssh/config`) to allow it to connect.
> 
> 
> 
> (Added to wiki: https://github.com/samuelthomas2774/airport/wiki/SSH#airport-host-key-types.)

Thanks for the reply this works correctly.
